volumes:
  postgres-data:

networks:
  common-net:
    driver: bridge

services:
  professions_api:
    container_name: professions-api
    build:
      context: .
      dockerfile: Professions.Api/Dockerfile 
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: 5000
    networks:
      - common-net
    depends_on:
      postgres_db:
        condition: service_healthy
  
  postgres_db:
    container_name: postgres-professions
    image: postgres:17.2
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: professions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nigPostgres_Pas5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - common-net