// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Professions.Infrastructure;

#nullable disable

namespace Professions.Infrastructure.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20250920130121_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Professions.Domain.Entities.BaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("Professions.Domain.Entities.ProfessionSkillEntity", b =>
                {
                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("SkillId", "ProfessionId", "Level");

                    b.HasIndex("ProfessionId");

                    b.ToTable("profession_skills", (string)null);

                    b.HasData(
                        new
                        {
                            SkillId = new Guid("45c6d15c-a58c-4ad0-a68b-b8f88c6ece93"),
                            ProfessionId = new Guid("3baf2a20-6e44-4586-bf39-6fa7caa5aa03"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("9d849fb7-6007-443d-9b3a-676ef72edbb4"),
                            ProfessionId = new Guid("3baf2a20-6e44-4586-bf39-6fa7caa5aa03"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("5ae23d6d-b8ef-4240-8bc6-ef883444f791"),
                            ProfessionId = new Guid("3baf2a20-6e44-4586-bf39-6fa7caa5aa03"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("2669521c-2632-48c9-81d8-469a3de63869"),
                            ProfessionId = new Guid("3baf2a20-6e44-4586-bf39-6fa7caa5aa03"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("0b11d0b8-972f-449b-8ba3-99e120168e06"),
                            ProfessionId = new Guid("3baf2a20-6e44-4586-bf39-6fa7caa5aa03"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("12af686c-7f56-453c-bcfb-5b0b511478b6"),
                            ProfessionId = new Guid("3baf2a20-6e44-4586-bf39-6fa7caa5aa03"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("27519c94-1cf9-4dbb-9d17-c921849db12b"),
                            ProfessionId = new Guid("3baf2a20-6e44-4586-bf39-6fa7caa5aa03"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("b702b46b-5695-47df-aac5-d6427cefc95b"),
                            ProfessionId = new Guid("3baf2a20-6e44-4586-bf39-6fa7caa5aa03"),
                            Level = 3
                        },
                        new
                        {
                            SkillId = new Guid("6bd3ea61-f565-4af8-862f-49a442baa79f"),
                            ProfessionId = new Guid("7e2b1b35-6211-4157-9a11-2e3214fced85"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("73bfc8f1-a319-4912-a3cb-006dee8bb53c"),
                            ProfessionId = new Guid("7e2b1b35-6211-4157-9a11-2e3214fced85"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("89301f93-9fa0-4e0c-a76f-d63ca8686c83"),
                            ProfessionId = new Guid("7e2b1b35-6211-4157-9a11-2e3214fced85"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("2669521c-2632-48c9-81d8-469a3de63869"),
                            ProfessionId = new Guid("7e2b1b35-6211-4157-9a11-2e3214fced85"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("71cfcbd8-832a-451f-916e-c158f229698b"),
                            ProfessionId = new Guid("7e2b1b35-6211-4157-9a11-2e3214fced85"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("8ebb9b00-e970-4fbe-8864-bbc3c2ab7e7b"),
                            ProfessionId = new Guid("7e2b1b35-6211-4157-9a11-2e3214fced85"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("d5634588-7459-4c4e-9a1b-23de9a78dc44"),
                            ProfessionId = new Guid("7e2b1b35-6211-4157-9a11-2e3214fced85"),
                            Level = 3
                        },
                        new
                        {
                            SkillId = new Guid("b68e288f-432e-4e79-93e2-5d3134ddd7ab"),
                            ProfessionId = new Guid("7e2b1b35-6211-4157-9a11-2e3214fced85"),
                            Level = 3
                        },
                        new
                        {
                            SkillId = new Guid("6c9a43be-804a-4e83-9664-6452b274c513"),
                            ProfessionId = new Guid("7e2b1b35-6211-4157-9a11-2e3214fced85"),
                            Level = 3
                        },
                        new
                        {
                            SkillId = new Guid("45c6d15c-a58c-4ad0-a68b-b8f88c6ece93"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("9d849fb7-6007-443d-9b3a-676ef72edbb4"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("5ae23d6d-b8ef-4240-8bc6-ef883444f791"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("0b11d0b8-972f-449b-8ba3-99e120168e06"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("73bfc8f1-a319-4912-a3cb-006dee8bb53c"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("6bd3ea61-f565-4af8-862f-49a442baa79f"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("89301f93-9fa0-4e0c-a76f-d63ca8686c83"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("2669521c-2632-48c9-81d8-469a3de63869"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("97309ec7-defe-4f94-b7ae-3d027a26029d"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("71cfcbd8-832a-451f-916e-c158f229698b"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("9863b431-7907-4173-8d9a-0bcaf9374589"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("a177c46b-2a87-48bc-89c8-f10b47c1d633"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("27519c94-1cf9-4dbb-9d17-c921849db12b"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("5e1497e4-ae25-4142-a41e-cf58f20793ba"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 3
                        },
                        new
                        {
                            SkillId = new Guid("b68e288f-432e-4e79-93e2-5d3134ddd7ab"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 3
                        },
                        new
                        {
                            SkillId = new Guid("d5634588-7459-4c4e-9a1b-23de9a78dc44"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 3
                        },
                        new
                        {
                            SkillId = new Guid("b702b46b-5695-47df-aac5-d6427cefc95b"),
                            ProfessionId = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            Level = 3
                        },
                        new
                        {
                            SkillId = new Guid("a0be2b76-976c-4954-b13f-bd4fbf6cc315"),
                            ProfessionId = new Guid("7bb487e3-9997-46e4-aed8-84fe2839a0e5"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("aeb668ff-9ba4-4a9e-b097-cf050bf5b42b"),
                            ProfessionId = new Guid("7bb487e3-9997-46e4-aed8-84fe2839a0e5"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("d4b7f267-27b6-4c47-b53f-6d15b6340781"),
                            ProfessionId = new Guid("7bb487e3-9997-46e4-aed8-84fe2839a0e5"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("cae35984-265c-43e8-96e3-94d200398436"),
                            ProfessionId = new Guid("7bb487e3-9997-46e4-aed8-84fe2839a0e5"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("b8b19c53-3729-4b50-92cc-e05c43f303f3"),
                            ProfessionId = new Guid("7bb487e3-9997-46e4-aed8-84fe2839a0e5"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("b8b19c53-3729-4b50-92cc-e05c43f303f3"),
                            ProfessionId = new Guid("7bb487e3-9997-46e4-aed8-84fe2839a0e5"),
                            Level = 3
                        },
                        new
                        {
                            SkillId = new Guid("f770f0ca-164f-4f41-85a5-05d042416b8a"),
                            ProfessionId = new Guid("58682ecf-0ac9-4f3a-a62a-65090dfdad69"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("679d6428-0ed2-4e72-ac0b-2e4f0e03a6e7"),
                            ProfessionId = new Guid("58682ecf-0ac9-4f3a-a62a-65090dfdad69"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("a9efd608-83e6-4a62-9a16-ff16d7f8efbf"),
                            ProfessionId = new Guid("58682ecf-0ac9-4f3a-a62a-65090dfdad69"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("9b087a12-5142-454d-b205-5b8a1bd4603b"),
                            ProfessionId = new Guid("58682ecf-0ac9-4f3a-a62a-65090dfdad69"),
                            Level = 3
                        },
                        new
                        {
                            SkillId = new Guid("28c29fa0-7aec-4f3b-8184-3fa214d4a7c4"),
                            ProfessionId = new Guid("37d1dc2d-a920-489e-9add-c585b49ca186"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("ea329312-6c7b-4092-b131-d7faf8b810d8"),
                            ProfessionId = new Guid("37d1dc2d-a920-489e-9add-c585b49ca186"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("23660949-a2a5-4700-b333-ed0bee0c3a42"),
                            ProfessionId = new Guid("37d1dc2d-a920-489e-9add-c585b49ca186"),
                            Level = 1
                        },
                        new
                        {
                            SkillId = new Guid("00a2affd-5ea7-4c64-b44c-df8ed6c44c9b"),
                            ProfessionId = new Guid("37d1dc2d-a920-489e-9add-c585b49ca186"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("7e03a0b7-850f-42f5-8664-7f819dba625c"),
                            ProfessionId = new Guid("37d1dc2d-a920-489e-9add-c585b49ca186"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("83e797ab-d048-4d06-8260-33a9d695ac32"),
                            ProfessionId = new Guid("37d1dc2d-a920-489e-9add-c585b49ca186"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("c850290c-5e3f-4abe-b370-2e8d0cb5a3b4"),
                            ProfessionId = new Guid("37d1dc2d-a920-489e-9add-c585b49ca186"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("02892dea-3bc5-4c90-915c-56e3ec0b61d0"),
                            ProfessionId = new Guid("37d1dc2d-a920-489e-9add-c585b49ca186"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("7508a871-70a0-44b3-94d9-ea90df02129b"),
                            ProfessionId = new Guid("37d1dc2d-a920-489e-9add-c585b49ca186"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("8fade48d-dd25-4869-b19f-4cf944b91fce"),
                            ProfessionId = new Guid("37d1dc2d-a920-489e-9add-c585b49ca186"),
                            Level = 2
                        },
                        new
                        {
                            SkillId = new Guid("23ed6db0-aaf6-4bf8-b0bb-8e3a6564ffba"),
                            ProfessionId = new Guid("37d1dc2d-a920-489e-9add-c585b49ca186"),
                            Level = 3
                        },
                        new
                        {
                            SkillId = new Guid("d5736426-981e-44bf-9e48-6ab38def4ee9"),
                            ProfessionId = new Guid("37d1dc2d-a920-489e-9add-c585b49ca186"),
                            Level = 3
                        },
                        new
                        {
                            SkillId = new Guid("1855bccc-35ed-4026-b560-53d48cc04f1d"),
                            ProfessionId = new Guid("00953951-2737-46d6-9c6e-c2be1a81d925"),
                            Level = 0
                        },
                        new
                        {
                            SkillId = new Guid("3de32036-7524-4843-99a3-59bb6847adde"),
                            ProfessionId = new Guid("00953951-2737-46d6-9c6e-c2be1a81d925"),
                            Level = 0
                        },
                        new
                        {
                            SkillId = new Guid("6e74f32e-de01-49f5-bd5d-dd928b172267"),
                            ProfessionId = new Guid("00953951-2737-46d6-9c6e-c2be1a81d925"),
                            Level = 0
                        },
                        new
                        {
                            SkillId = new Guid("54b97981-2e1e-4954-91b5-55947b874d59"),
                            ProfessionId = new Guid("00953951-2737-46d6-9c6e-c2be1a81d925"),
                            Level = 0
                        },
                        new
                        {
                            SkillId = new Guid("cc83e336-f920-48ba-af4f-c5016427a8f5"),
                            ProfessionId = new Guid("8ef53ba4-881c-4f4f-8db4-175e9a92a181"),
                            Level = 0
                        },
                        new
                        {
                            SkillId = new Guid("949e526b-be0b-40b3-9843-bf3fda3ae0eb"),
                            ProfessionId = new Guid("8ef53ba4-881c-4f4f-8db4-175e9a92a181"),
                            Level = 0
                        },
                        new
                        {
                            SkillId = new Guid("89301f93-9fa0-4e0c-a76f-d63ca8686c83"),
                            ProfessionId = new Guid("80736387-153f-4b56-9271-2476df6566cb"),
                            Level = 0
                        },
                        new
                        {
                            SkillId = new Guid("6bd3ea61-f565-4af8-862f-49a442baa79f"),
                            ProfessionId = new Guid("80736387-153f-4b56-9271-2476df6566cb"),
                            Level = 0
                        },
                        new
                        {
                            SkillId = new Guid("165d592f-3e67-440a-951e-03d334525a18"),
                            ProfessionId = new Guid("80736387-153f-4b56-9271-2476df6566cb"),
                            Level = 0
                        },
                        new
                        {
                            SkillId = new Guid("8e881b7c-255a-478d-ae39-bb321b21cec4"),
                            ProfessionId = new Guid("80736387-153f-4b56-9271-2476df6566cb"),
                            Level = 0
                        });
                });

            modelBuilder.Entity("Professions.Domain.Entities.IndustryEntity", b =>
                {
                    b.HasBaseType("Professions.Domain.Entities.BaseEntity");

                    b.Property<string>("IndustryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("industry_name");

                    b.HasIndex("IndustryName")
                        .IsUnique()
                        .HasDatabaseName("INX_INDUSTRY_NAME");

                    b.ToTable("industries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8530f0a0-14de-4a1c-acbc-4279acb79034"),
                            IndustryName = "IT и технологии"
                        },
                        new
                        {
                            Id = new Guid("a338e31c-41aa-4d10-9439-4f02a990e28c"),
                            IndustryName = "Маркетинг и продажи"
                        },
                        new
                        {
                            Id = new Guid("2ef8c75d-b9ae-49e4-a3a3-79d8fc3bba22"),
                            IndustryName = "Другое"
                        });
                });

            modelBuilder.Entity("Professions.Domain.Entities.ProfessionEntity", b =>
                {
                    b.HasBaseType("Professions.Domain.Entities.BaseEntity");

                    b.Property<Guid>("IndustryId")
                        .HasColumnType("uuid")
                        .HasColumnName("industry_id");

                    b.Property<string>("ProfessionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("profession_name");

                    b.HasIndex("IndustryId");

                    b.HasIndex("ProfessionName")
                        .IsUnique()
                        .HasDatabaseName("INX_PROFESSION_NAME");

                    b.ToTable("professions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3baf2a20-6e44-4586-bf39-6fa7caa5aa03"),
                            IndustryId = new Guid("8530f0a0-14de-4a1c-acbc-4279acb79034"),
                            ProfessionName = "Frontend-разработчик"
                        },
                        new
                        {
                            Id = new Guid("7e2b1b35-6211-4157-9a11-2e3214fced85"),
                            IndustryId = new Guid("8530f0a0-14de-4a1c-acbc-4279acb79034"),
                            ProfessionName = "Backend-разработчик"
                        },
                        new
                        {
                            Id = new Guid("945f817b-faf1-4db0-a90b-dcddb215e70b"),
                            IndustryId = new Guid("8530f0a0-14de-4a1c-acbc-4279acb79034"),
                            ProfessionName = "Fullstack-разработчик"
                        },
                        new
                        {
                            Id = new Guid("7bb487e3-9997-46e4-aed8-84fe2839a0e5"),
                            IndustryId = new Guid("a338e31c-41aa-4d10-9439-4f02a990e28c"),
                            ProfessionName = "Brand-менеджер"
                        },
                        new
                        {
                            Id = new Guid("58682ecf-0ac9-4f3a-a62a-65090dfdad69"),
                            IndustryId = new Guid("a338e31c-41aa-4d10-9439-4f02a990e28c"),
                            ProfessionName = "Продакт-маркетолог"
                        },
                        new
                        {
                            Id = new Guid("37d1dc2d-a920-489e-9add-c585b49ca186"),
                            IndustryId = new Guid("a338e31c-41aa-4d10-9439-4f02a990e28c"),
                            ProfessionName = "Копирайтер"
                        },
                        new
                        {
                            Id = new Guid("00953951-2737-46d6-9c6e-c2be1a81d925"),
                            IndustryId = new Guid("2ef8c75d-b9ae-49e4-a3a3-79d8fc3bba22"),
                            ProfessionName = "Эколог"
                        },
                        new
                        {
                            Id = new Guid("8ef53ba4-881c-4f4f-8db4-175e9a92a181"),
                            IndustryId = new Guid("a338e31c-41aa-4d10-9439-4f02a990e28c"),
                            ProfessionName = "Менеджер магазина"
                        },
                        new
                        {
                            Id = new Guid("80736387-153f-4b56-9271-2476df6566cb"),
                            IndustryId = new Guid("8530f0a0-14de-4a1c-acbc-4279acb79034"),
                            ProfessionName = "Продакт-аналитик"
                        });
                });

            modelBuilder.Entity("Professions.Domain.Entities.SkillEntity", b =>
                {
                    b.HasBaseType("Professions.Domain.Entities.BaseEntity");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("skill_name");

                    b.HasIndex("SkillName")
                        .IsUnique()
                        .HasDatabaseName("INX_SKILL_NAME");

                    b.ToTable("skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2669521c-2632-48c9-81d8-469a3de63869"),
                            SkillName = "Git"
                        },
                        new
                        {
                            Id = new Guid("27519c94-1cf9-4dbb-9d17-c921849db12b"),
                            SkillName = "Код-ревью"
                        },
                        new
                        {
                            Id = new Guid("9863b431-7907-4173-8d9a-0bcaf9374589"),
                            SkillName = "Jenkins"
                        },
                        new
                        {
                            Id = new Guid("a177c46b-2a87-48bc-89c8-f10b47c1d633"),
                            SkillName = "GitHub Actions"
                        },
                        new
                        {
                            Id = new Guid("b702b46b-5695-47df-aac5-d6427cefc95b"),
                            SkillName = "Оптимизация"
                        },
                        new
                        {
                            Id = new Guid("45c6d15c-a58c-4ad0-a68b-b8f88c6ece93"),
                            SkillName = "HTML"
                        },
                        new
                        {
                            Id = new Guid("9d849fb7-6007-443d-9b3a-676ef72edbb4"),
                            SkillName = "CSS"
                        },
                        new
                        {
                            Id = new Guid("5ae23d6d-b8ef-4240-8bc6-ef883444f791"),
                            SkillName = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("12af686c-7f56-453c-bcfb-5b0b511478b6"),
                            SkillName = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("0b11d0b8-972f-449b-8ba3-99e120168e06"),
                            SkillName = "React"
                        },
                        new
                        {
                            Id = new Guid("6bd3ea61-f565-4af8-862f-49a442baa79f"),
                            SkillName = "Python (Django/Flask/FastAPI)"
                        },
                        new
                        {
                            Id = new Guid("73bfc8f1-a319-4912-a3cb-006dee8bb53c"),
                            SkillName = "Node.js (Express/NestJS)"
                        },
                        new
                        {
                            Id = new Guid("89301f93-9fa0-4e0c-a76f-d63ca8686c83"),
                            SkillName = "SQL (PostgreSQL/MySQL)"
                        },
                        new
                        {
                            Id = new Guid("71cfcbd8-832a-451f-916e-c158f229698b"),
                            SkillName = "REST"
                        },
                        new
                        {
                            Id = new Guid("8ebb9b00-e970-4fbe-8864-bbc3c2ab7e7b"),
                            SkillName = "Docker"
                        },
                        new
                        {
                            Id = new Guid("d5634588-7459-4c4e-9a1b-23de9a78dc44"),
                            SkillName = "Микросервисы"
                        },
                        new
                        {
                            Id = new Guid("b68e288f-432e-4e79-93e2-5d3134ddd7ab"),
                            SkillName = "AWS/GCP/Azure"
                        },
                        new
                        {
                            Id = new Guid("6c9a43be-804a-4e83-9664-6452b274c513"),
                            SkillName = "Масштабирование"
                        },
                        new
                        {
                            Id = new Guid("97309ec7-defe-4f94-b7ae-3d027a26029d"),
                            SkillName = "Angular"
                        },
                        new
                        {
                            Id = new Guid("5e1497e4-ae25-4142-a41e-cf58f20793ba"),
                            SkillName = "AWS EC2"
                        },
                        new
                        {
                            Id = new Guid("a0be2b76-976c-4954-b13f-bd4fbf6cc315"),
                            SkillName = "SWOT (Miro)"
                        },
                        new
                        {
                            Id = new Guid("aeb668ff-9ba4-4a9e-b097-cf050bf5b42b"),
                            SkillName = "SurveyMonkey"
                        },
                        new
                        {
                            Id = new Guid("d4b7f267-27b6-4c47-b53f-6d15b6340781"),
                            SkillName = "Google Forms"
                        },
                        new
                        {
                            Id = new Guid("cae35984-265c-43e8-96e3-94d200398436"),
                            SkillName = "Canva"
                        },
                        new
                        {
                            Id = new Guid("b8b19c53-3729-4b50-92cc-e05c43f303f3"),
                            SkillName = "Adobe Illustrator"
                        },
                        new
                        {
                            Id = new Guid("f770f0ca-164f-4f41-85a5-05d042416b8a"),
                            SkillName = "Productboard"
                        },
                        new
                        {
                            Id = new Guid("679d6428-0ed2-4e72-ac0b-2e4f0e03a6e7"),
                            SkillName = "SimilarWeb"
                        },
                        new
                        {
                            Id = new Guid("a9efd608-83e6-4a62-9a16-ff16d7f8efbf"),
                            SkillName = "Crunchbase"
                        },
                        new
                        {
                            Id = new Guid("9b087a12-5142-454d-b205-5b8a1bd4603b"),
                            SkillName = "AARRR-модель"
                        },
                        new
                        {
                            Id = new Guid("28c29fa0-7aec-4f3b-8184-3fa214d4a7c4"),
                            SkillName = "Google Docs"
                        },
                        new
                        {
                            Id = new Guid("00a2affd-5ea7-4c64-b44c-df8ed6c44c9b"),
                            SkillName = "Notion"
                        },
                        new
                        {
                            Id = new Guid("ea329312-6c7b-4092-b131-d7faf8b810d8"),
                            SkillName = "Grammarly"
                        },
                        new
                        {
                            Id = new Guid("23660949-a2a5-4700-b333-ed0bee0c3a42"),
                            SkillName = "Yoast SEO"
                        },
                        new
                        {
                            Id = new Guid("7e03a0b7-850f-42f5-8664-7f819dba625c"),
                            SkillName = "SEMrush"
                        },
                        new
                        {
                            Id = new Guid("83e797ab-d048-4d06-8260-33a9d695ac32"),
                            SkillName = "WordPress"
                        },
                        new
                        {
                            Id = new Guid("c850290c-5e3f-4abe-b370-2e8d0cb5a3b4"),
                            SkillName = "Tilda"
                        },
                        new
                        {
                            Id = new Guid("02892dea-3bc5-4c90-915c-56e3ec0b61d0"),
                            SkillName = "Wix"
                        },
                        new
                        {
                            Id = new Guid("7508a871-70a0-44b3-94d9-ea90df02129b"),
                            SkillName = "Сторителлинг"
                        },
                        new
                        {
                            Id = new Guid("8fade48d-dd25-4869-b19f-4cf944b91fce"),
                            SkillName = "Маркетинг и психология рекламы"
                        },
                        new
                        {
                            Id = new Guid("23ed6db0-aaf6-4bf8-b0bb-8e3a6564ffba"),
                            SkillName = "SEO-стратегии"
                        },
                        new
                        {
                            Id = new Guid("d5736426-981e-44bf-9e48-6ab38def4ee9"),
                            SkillName = "Адаптация под ЦА"
                        },
                        new
                        {
                            Id = new Guid("1855bccc-35ed-4026-b560-53d48cc04f1d"),
                            SkillName = "ISO 14001"
                        },
                        new
                        {
                            Id = new Guid("3de32036-7524-4843-99a3-59bb6847adde"),
                            SkillName = "SimaPro"
                        },
                        new
                        {
                            Id = new Guid("6e74f32e-de01-49f5-bd5d-dd928b172267"),
                            SkillName = "Advocacy"
                        },
                        new
                        {
                            Id = new Guid("54b97981-2e1e-4954-91b5-55947b874d59"),
                            SkillName = "Экология"
                        },
                        new
                        {
                            Id = new Guid("cc83e336-f920-48ba-af4f-c5016427a8f5"),
                            SkillName = "RetailNext"
                        },
                        new
                        {
                            Id = new Guid("949e526b-be0b-40b3-9843-bf3fda3ae0eb"),
                            SkillName = "Team management"
                        },
                        new
                        {
                            Id = new Guid("165d592f-3e67-440a-951e-03d334525a18"),
                            SkillName = "Optimizely"
                        },
                        new
                        {
                            Id = new Guid("8e881b7c-255a-478d-ae39-bb321b21cec4"),
                            SkillName = "Data-driven"
                        });
                });

            modelBuilder.Entity("Professions.Domain.Entities.ProfessionSkillEntity", b =>
                {
                    b.HasOne("Professions.Domain.Entities.ProfessionEntity", "Profession")
                        .WithMany("Skills")
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Professions.Domain.Entities.SkillEntity", "Skill")
                        .WithMany("Professions")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profession");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Professions.Domain.Entities.ProfessionEntity", b =>
                {
                    b.HasOne("Professions.Domain.Entities.IndustryEntity", "Industry")
                        .WithMany("Professions")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("Professions.Domain.Entities.IndustryEntity", b =>
                {
                    b.Navigation("Professions");
                });

            modelBuilder.Entity("Professions.Domain.Entities.ProfessionEntity", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Professions.Domain.Entities.SkillEntity", b =>
                {
                    b.Navigation("Professions");
                });
#pragma warning restore 612, 618
        }
    }
}
